### ISSUE TITLE
style problem and render question

### ISSUE THREAD

**Issue by loveklmn** [kerasus/vue-tiptap-katex#29]
Hi, kerasus.

this repo is extremely meaningful. I appreciate your work. I have two questions about this repo.

1. style problem
When I try to use the component, here comes this question. minimal reproduce link here. https://codesandbox.io/s/little-http-589gu?file=/src/App.vue

2. render problem
When I tried to use the formula, I use `$` and nothing happens. I wonder whether the formula could only be triggered by clicking the icon on bars.

**Comment by neokazemi** [comment]
Hi.
1: The problem that causes style issues in the codesandbox that you create is that none of the editor's dependencies are installed. For example check your package.json for Vuetify. I can dig into it more if you provide me your package.json and a screenshot of how your editor looks.
2: YES. Because of the performance concerns, at this moment you can only create a formula box by clicking on the formula button.

**Comment by loveklmn** [comment]
Hi, @neokazemi.

1. I have installed vuetify [here](https://codesandbox.io/s/little-http-589gu?file=/package.json). The style problem still exists. (If any solutions could be proposed, just do it on code sandbox and paste a new link here. I really appreciate it.)
2. Thanks for clarifying this issue. Thanks!

**Comment by neokazemi** [comment]
I've installed Vuetify and some other necessary dependencies [here](https://codesandbox.io/s/sleepy-haibt-te4o5?file=/src/main.js).
You should use Vuetify in Vue (look at the main.js and plugins/vuetify.js files).
